export const DEFAULT_SETTINGS = {
  businessName: 'Elizabeth Méndez',
  tradeName: 'Costura y confección',
  taxId: '',
  phone: '',
  whatsapp: '',
  email: '',
  address: '',
  city: 'Santo Domingo',
  country: 'República Dominicana',
  logo: '',
  prefix: 'COT',
  nextNumber: 1,
  defaultCurrency: 'DOP',
  defaultTax: 18,
  defaultValidity: 15,
  defaultNotes: 'Gracias por confiar en mi trabajo de costura. Estoy a tu disposición para cualquier ajuste.',
  defaultTerms: 'La cotización tiene una validez de 15 días. El inicio del trabajo se coordina al aprobar el diseño, las medidas y los materiales.',
};
