import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { Activity, ArrowRight, BadgeCheck, FileText, Plus, Send, Sparkles, Users, Wallet } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Button, Card, EmptyState, PageHeader, StatusBadge } from '../components/ui.jsx';
import StatCard from '../components/StatCard.jsx';
import { dataStore } from '../services/dataStore.js';
import { CURRENCY_INFO, formatMoney, quoteTotals, statusForDisplay } from '../utils/quoteUtils.js';

const months = ['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'];
export default function Dashboard() {
  const [currency, setCurrency] = useState(dataStore.settings.get().defaultCurrency || 'DOP');
  const clients = dataStore.clients.list();
  const quotes = dataStore.quotes.list().map((quote) => ({ ...quote, status: statusForDisplay(quote) }));
  const rate = (quoteCurrency) => CURRENCY_INFO[quoteCurrency]?.rate || 1;
  const amountInCurrency = (quote) => quoteTotals(quote.items).total * rate(quote.currency) / rate(currency);
  const stats = useMemo(() => {
    const total = quotes.reduce((sum, quote) => sum + amountInCurrency(quote), 0);
    return { total, pending: quotes.filter((quote) => ['pending','sent'].includes(quote.status)).length, approved: quotes.filter((quote) => quote.status === 'approved').length };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [quotes, currency]);
  const chartData = months.map((month, index) => ({ month, total: quotes.filter((quote) => {const d=new Date(`${quote.date}T12:00:00`);return d.getMonth()===index&&d.getFullYear()===new Date().getFullYear();}).reduce((sum, quote) => sum + amountInCurrency(quote),0) }));
  const ranked = clients.map((client) => ({ client, total: quotes.filter((quote) => quote.clientId === client.id).reduce((sum, quote) => sum + amountInCurrency(quote),0) })).sort((a,b)=>b.total-a.total).slice(0,4);
  const latest = [...quotes].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);
  const activity = (quote) => { const client=clients.find((entry)=>entry.id===quote.clientId); return <div className="activity-row" key={quote.id}><div className="activity-icon"><FileText size={17}/></div><div className="activity-main"><Link to={`/cotizaciones/${quote.id}`}><strong>{quote.number}</strong></Link><span>{client?.businessName||client?.name||'Cliente eliminado'}</span></div><div className="activity-amount"><strong>{formatMoney(amountInCurrency(quote),currency)}</strong><StatusBadge status={quote.status}/></div></div>; };
  return <><PageHeader eyebrow="VISTA GENERAL" title="Hola, Elizabeth" description="Cotiza tus confecciones, arreglos y prendas a medida desde un solo lugar." action={<div className="dashboard-actions"><label className="currency-picker"><span>Ver en</span><select value={currency} onChange={(e)=>setCurrency(e.target.value)} aria-label="Moneda de visualización"><option value="DOP">DOP · Peso dominicano</option><option value="USD">USD · Dólar estadounidense</option></select></label><Link className="btn btn-primary" to="/cotizaciones/nueva"><Plus size={17}/> Nueva cotización</Link></div>}/>
    <div className="stat-grid"><StatCard label="TOTAL COTIZADO" value={formatMoney(stats.total,currency)} detail={`${quotes.length} cotizaciones emitidas`} icon={Wallet} tone="olive"/><StatCard label="COTIZACIONES" value={quotes.length} detail={`${clients.length} clientes registrados`} icon={FileText} tone="sand"/><StatCard label="PENDIENTES" value={stats.pending} detail="Por revisar o responder" icon={Send} tone="amber"/><StatCard label="APROBADAS" value={stats.approved} detail="Propuestas aceptadas" icon={BadgeCheck} tone="green"/></div>
    <div className="dashboard-grid"><Card className="chart-card"><div className="section-heading"><div><div className="eyebrow">SEGUIMIENTO</div><h2>Cotizaciones mensuales</h2><p>Monto cotizado durante este año</p></div><span className="chart-legend"><i/> Cotizado</span></div><div className="chart-area"><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData} margin={{top:12,right:6,left:4,bottom:0}}><defs><linearGradient id="oliveBar" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#8fae5d"/><stop offset="100%" stopColor="#536b32"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#edf0e9"/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fill:'#899184',fontSize:11}} dy={9}/><YAxis axisLine={false} tickLine={false} tick={{fill:'#899184',fontSize:10}} width={46} tickFormatter={(value)=>value>999?`${Math.round(value/1000)}k`:value}/><Tooltip formatter={(value)=>formatMoney(value,currency)} cursor={{fill:'#f4f6f0'}} contentStyle={{border:'1px solid #dce4d4',borderRadius:12,fontSize:12}}/><Bar dataKey="total" radius={[6,6,2,2]} maxBarSize={32}>{chartData.map((entry,index)=><Cell key={entry.month} fill={entry.total?'url(#oliveBar)':'#e9eee3'} opacity={index===new Date().getMonth()?1:.9}/>)}</Bar></BarChart></ResponsiveContainer></div></Card>
      <Card className="ranking-card"><div className="section-heading"><div><div className="eyebrow">RELACIONES</div><h2>Mejores clientes</h2><p>Por monto cotizado</p></div><Users size={18} className="heading-icon"/></div><div className="ranking-list">{ranked.filter((entry)=>entry.total>0).length?ranked.filter((entry)=>entry.total>0).map(({client,total},index)=><Link to="/clientes" className="rank-row" key={client.id}><span className={`rank-number ${index===0?'rank-first':''}`}>{String(index+1).padStart(2,'0')}</span><span className="rank-avatar">{(client.businessName||client.name).slice(0,1).toUpperCase()}</span><span className="rank-name"><strong>{client.businessName||client.name}</strong><small>{client.name}</small></span><strong className="rank-total">{formatMoney(total,currency)}</strong></Link>):<EmptyState icon={Users} title="Aún no hay actividad" description="Al guardar cotizaciones aparecerán aquí tus principales clientes."/>}</div></Card></div>
    <div className="bottom-grid"><Card className="activity-card"><div className="section-heading"><div><div className="eyebrow">LO MÁS RECIENTE</div><h2>Actividad reciente</h2><p>Últimos movimientos de cotización</p></div><Link className="text-link" to="/cotizaciones">Ver todas <ArrowRight size={15}/></Link></div>{latest.length?<div className="activity-list">{latest.map(activity)}</div>:<EmptyState icon={Activity} title="Sin cotizaciones todavía" description="Crea tu primera cotización de costura y aparecerá aquí." action={<Link to="/cotizaciones/nueva"><Button><Plus size={16}/> Nueva cotización</Button></Link>}/>}</Card><Card className="welcome-card"><span className="welcome-spark"><Sparkles size={19}/></span><div className="eyebrow">COSTURA HECHA A TU MEDIDA</div><h2>Tu próximo trabajo comienza aquí.</h2><p>Cotiza prendas, confecciones y arreglos, y mantén cada trabajo organizado.</p><Link to="/cotizaciones/nueva" className="welcome-link">Crear cotización <ArrowRight size={15}/></Link><div className="welcome-decoration"><span/><span/><span/></div></Card></div>
  </>;
}
