import { useRef, useState } from 'react';
import { BadgeCheck, Building2, FileText, RotateCcw, Save, Settings2, Upload, X } from 'lucide-react';
import { Button, Card, ConfirmDialog, Field, PageHeader, Select } from '../components/ui.jsx';
import { dataStore } from '../services/dataStore.js';
import { useOutletContext } from 'react-router-dom';

export default function SettingsPage(){
  const [form,setForm]=useState(()=>dataStore.settings.get());const [confirmReset,setConfirmReset]=useState(false);const inputRef=useRef(null);const formRef=useRef(null);const {notify}=useOutletContext();
  const update=(key,value)=>setForm((current)=>({...current,[key]:value}));
  const save=(event)=>{event.preventDefault();if(!form.businessName.trim())return notify('El nombre del negocio es obligatorio.','error');const next={...form,prefix:form.prefix.trim().toUpperCase()||'COT',nextNumber:Math.max(1,Number(form.nextNumber)||1),defaultTax:Math.max(0,Number(form.defaultTax)||0),defaultValidity:Math.max(1,Number(form.defaultValidity)||15)};dataStore.settings.save(next);setForm(next);notify('Configuración guardada correctamente.');};
  const uploadLogo=(file)=>{if(!file)return;if(!['image/png','image/jpeg'].includes(file.type))return notify('El logo debe estar en formato PNG o JPG.','error');if(file.size>2*1024*1024)return notify('El logo debe pesar menos de 2 MB.','error');const reader=new FileReader();reader.onload=()=>update('logo',reader.result);reader.readAsDataURL(file);};
  const restore=()=>{dataStore.settings.resetDemo();setForm(dataStore.settings.get());setConfirmReset(false);notify('Datos de demostración restaurados.');};
  return <><PageHeader eyebrow="PREFERENCIAS" title="Configuración" description="Personaliza los datos de tu negocio y tus cotizaciones." action={<Button onClick={()=>formRef.current?.requestSubmit()}><Save size={16}/> Guardar cambios</Button>}/><form ref={formRef} className="settings-form" onSubmit={save}>
    <Card className="settings-card"><div className="settings-card-heading"><span className="section-icon"><Building2 size={18}/></span><div><h2>Información del negocio</h2><p>Estos datos aparecerán en tus documentos comerciales.</p></div></div><div className="logo-upload-row"><div className="logo-preview">{form.logo?<img src={form.logo} alt="Logo de negocio"/>:<span>EM</span>}</div><div className="logo-copy"><strong>Logo de tu negocio</strong><p>Usa una imagen cuadrada en formato PNG o JPG. Máximo 2 MB.</p><div className="logo-buttons"><input ref={inputRef} type="file" accept="image/png,image/jpeg" hidden onChange={(e)=>uploadLogo(e.target.files?.[0])}/><Button type="button" variant="outline" size="small" onClick={()=>inputRef.current?.click()}><Upload size={15}/> Subir logo</Button>{form.logo&&<Button type="button" variant="ghost" size="small" onClick={()=>update('logo','')}><X size={15}/> Quitar</Button>}</div></div></div><div className="form-grid"><Field label="Nombre / razón social *"><input required value={form.businessName} onChange={(e)=>update('businessName',e.target.value)}/></Field><Field label="Nombre comercial"><input value={form.tradeName} onChange={(e)=>update('tradeName',e.target.value)}/></Field><Field label="RNC / Cédula"><input value={form.taxId} onChange={(e)=>update('taxId',e.target.value)} placeholder="Opcional"/></Field><Field label="Teléfono"><input value={form.phone} onChange={(e)=>update('phone',e.target.value)}/></Field><Field label="WhatsApp"><input value={form.whatsapp} onChange={(e)=>update('whatsapp',e.target.value)}/></Field><Field label="Correo electrónico"><input type="email" value={form.email} onChange={(e)=>update('email',e.target.value)}/></Field><Field label="Dirección"><input value={form.address} onChange={(e)=>update('address',e.target.value)}/></Field><Field label="Ciudad"><input value={form.city} onChange={(e)=>update('city',e.target.value)}/></Field><Field label="País"><input value={form.country} onChange={(e)=>update('country',e.target.value)}/></Field></div></Card>
    <Card className="settings-card"><div className="settings-card-heading"><span className="section-icon"><FileText size={18}/></span><div><h2>Preferencias de cotización</h2><p>Valores predeterminados para agilizar la creación de propuestas.</p></div></div><div className="form-grid"><Field label="Prefijo de numeración"><input value={form.prefix} maxLength="8" onChange={(e)=>update('prefix',e.target.value)}/><span className="field-hint">Ejemplo: {form.prefix||'COT'}-{String(form.nextNumber||1).padStart(6,'0')}</span></Field><Field label="Próximo número"><input type="number" min="1" step="1" value={form.nextNumber} onChange={(e)=>update('nextNumber',e.target.value)}/></Field><Field label="Moneda predeterminada"><Select value={form.defaultCurrency} onChange={(e)=>update('defaultCurrency',e.target.value)}><option value="DOP">DOP — Peso dominicano</option><option value="USD">USD — Dólar estadounidense</option></Select></Field><Field label="Impuesto predeterminado (%)"><input type="number" min="0" step="0.01" value={form.defaultTax} onChange={(e)=>update('defaultTax',e.target.value)}/></Field><Field label="Validez predeterminada (días)"><input type="number" min="1" step="1" value={form.defaultValidity} onChange={(e)=>update('defaultValidity',e.target.value)}/></Field><Field label="Notas predeterminadas" className="field-wide"><textarea rows="3" value={form.defaultNotes} onChange={(e)=>update('defaultNotes',e.target.value)}/></Field><Field label="Términos y condiciones predeterminados" className="field-wide"><textarea rows="3" value={form.defaultTerms} onChange={(e)=>update('defaultTerms',e.target.value)}/></Field></div><div className="settings-tip"><BadgeCheck size={17}/><span>Estos valores se aplicarán automáticamente a las nuevas cotizaciones. Siempre podrás ajustarlos antes de guardar.</span></div></Card>
    <Card className="settings-card danger-zone"><div className="settings-card-heading"><span className="section-icon section-icon-muted"><Settings2 size={18}/></span><div><h2>Datos de demostración</h2><p>Restablece los datos ficticios iniciales de esta aplicación en este navegador.</p></div><Button type="button" variant="outline" onClick={()=>setConfirmReset(true)}><RotateCcw size={15}/> Restaurar demo</Button></div></Card>
    <div className="settings-save-mobile"><Button type="submit"><Save size={16}/> Guardar cambios</Button></div>
  </form>{confirmReset&&<ConfirmDialog title="¿Restaurar los datos de demostración?" message="Se reemplazarán los clientes, cotizaciones y preferencias guardadas localmente por los ejemplos iniciales." confirmLabel="Restaurar datos" onCancel={()=>setConfirmReset(false)} onConfirm={restore}/>}</>;
}
