import { useEffect, useRef, useState } from 'react';
import { BadgeCheck, Building2, FileText, Save, Upload, X } from 'lucide-react';
import { Button, Card, Field, PageHeader, Select, Spinner } from '../components/ui.jsx';
import { dataStore } from '../services/dataStore.js';
import { useOutletContext } from 'react-router-dom';
import { DEFAULT_SETTINGS } from '../services/defaults.js';

export default function SettingsPage(){
  const [form,setForm]=useState(DEFAULT_SETTINGS);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const inputRef=useRef(null);const formRef=useRef(null);const {notify}=useOutletContext();
  useEffect(()=>{dataStore.settings.get().then(setForm).catch((error)=>notify(error.message,'error')).finally(()=>setLoading(false));},[]);
  const update=(key,value)=>setForm((current)=>({...current,[key]:value}));
  const save=async(event)=>{event.preventDefault();if(!form.businessName.trim())return notify('El nombre del negocio es obligatorio.','error');const next={...form,prefix:form.prefix.trim().toUpperCase()||'COT',nextNumber:Math.max(1,Number(form.nextNumber)||1),defaultValidity:Math.max(1,Number(form.defaultValidity)||15)};setSaving(true);try{const saved=await dataStore.settings.save(next);setForm(saved);notify('Configuración guardada correctamente.');}catch(error){notify(error.message,'error');}finally{setSaving(false);}};
  const uploadLogo=(file)=>{if(!file)return;if(!['image/png','image/jpeg'].includes(file.type))return notify('El logo debe estar en formato PNG o JPG.','error');if(file.size>1024*1024)return notify('El logo debe pesar menos de 1 MB.','error');const reader=new FileReader();reader.onload=()=>update('logo',reader.result);reader.readAsDataURL(file);};
  if(loading)return <Spinner label="Cargando preferencias…"/>;
  return <><PageHeader eyebrow="PREFERENCIAS" title="Configuración" description="Personaliza los datos de tu negocio y tus cotizaciones." action={<Button disabled={saving} onClick={()=>formRef.current?.requestSubmit()}><Save size={16}/> Guardar cambios</Button>}/><form ref={formRef} className="settings-form" onSubmit={save}>
    <Card className="settings-card"><div className="settings-card-heading"><span className="section-icon"><Building2 size={18}/></span><div><h2>Información del negocio</h2><p>Estos datos aparecerán en tus documentos comerciales.</p></div></div><div className="logo-upload-row"><div className="logo-preview">{form.logo?<img src={form.logo} alt="Logo de negocio"/>:<span>EM</span>}</div><div className="logo-copy"><strong>Logo de tu negocio</strong><p>Usa una imagen cuadrada en formato PNG o JPG. Máximo 1 MB.</p><div className="logo-buttons"><input ref={inputRef} type="file" accept="image/png,image/jpeg" hidden onChange={(e)=>uploadLogo(e.target.files?.[0])}/><Button type="button" variant="outline" size="small" onClick={()=>inputRef.current?.click()}><Upload size={15}/> Subir logo</Button>{form.logo&&<Button type="button" variant="ghost" size="small" onClick={()=>update('logo','')}><X size={15}/> Quitar</Button>}</div></div></div><div className="form-grid"><Field label="Nombre / razón social *"><input required value={form.businessName} onChange={(e)=>update('businessName',e.target.value)}/></Field><Field label="Nombre comercial"><input value={form.tradeName} onChange={(e)=>update('tradeName',e.target.value)}/></Field><Field label="RNC / Cédula"><input value={form.taxId} onChange={(e)=>update('taxId',e.target.value)} placeholder="Opcional"/></Field><Field label="Teléfono"><input value={form.phone} onChange={(e)=>update('phone',e.target.value)}/></Field><Field label="WhatsApp"><input value={form.whatsapp} onChange={(e)=>update('whatsapp',e.target.value)}/></Field><Field label="Correo electrónico"><input type="email" value={form.email} onChange={(e)=>update('email',e.target.value)}/></Field><Field label="Dirección"><input value={form.address} onChange={(e)=>update('address',e.target.value)}/></Field><Field label="Ciudad"><input value={form.city} onChange={(e)=>update('city',e.target.value)}/></Field><Field label="País"><input value={form.country} onChange={(e)=>update('country',e.target.value)}/></Field></div></Card>
    <Card className="settings-card"><div className="settings-card-heading"><span className="section-icon"><FileText size={18}/></span><div><h2>Preferencias de cotización</h2><p>Valores predeterminados para agilizar la creación de propuestas.</p></div></div><div className="form-grid"><Field label="Prefijo de numeración"><input value={form.prefix} maxLength="8" onChange={(e)=>update('prefix',e.target.value)}/><span className="field-hint">Ejemplo: {form.prefix||'COT'}-{String(form.nextNumber||1).padStart(6,'0')}</span></Field><Field label="Próximo número"><input type="number" min="1" step="1" value={form.nextNumber} onChange={(e)=>update('nextNumber',e.target.value)}/></Field><Field label="Moneda predeterminada"><Select value={form.defaultCurrency} onChange={(e)=>update('defaultCurrency',e.target.value)}><option value="DOP">DOP — Peso dominicano</option><option value="USD">USD — Dólar estadounidense</option></Select></Field><Field label="Validez predeterminada (días)"><input type="number" min="1" step="1" value={form.defaultValidity} onChange={(e)=>update('defaultValidity',e.target.value)}/></Field><Field label="Notas predeterminadas" className="field-wide"><textarea rows="3" value={form.defaultNotes} onChange={(e)=>update('defaultNotes',e.target.value)}/></Field><Field label="Términos y condiciones predeterminados" className="field-wide"><textarea rows="3" value={form.defaultTerms} onChange={(e)=>update('defaultTerms',e.target.value)}/></Field></div><div className="settings-tip"><BadgeCheck size={17}/><span>Estos valores se aplicarán automáticamente a las nuevas cotizaciones. Siempre podrás ajustarlos antes de guardar.</span></div></Card>
    <div className="settings-save-mobile"><Button type="submit" disabled={saving}><Save size={16}/> Guardar cambios</Button></div>
  </form></>;
}
